### ISSUE TITLE
Update to latest XTRX GW is not recognized

### ISSUE THREAD

**Issue by Jojeker** [myriadrf/LimeSDR-XTRX_GW#1]
Hello,

we just updated the LimeSDR XTRX via the latest bin file on the master branch, i.e. the 1.11 image from https://github.com/myriadrf/LimeSDR-XTRX_GW/blob/b4a7347c6f5a117f1bd425ee5f7075cb38f93e61/bitstream/flash_programming_file.bin and used the instructions found here https://github.com/myriadrf/LimeSuiteNG/issues/22#issuecomment-2083275915.

After upgrading the gateware, we are unable to see the device via `lspci | grep Xilinx`. We have a second board to rule out any issues with the computer and used a second computer to make sure that the device is indeed not recognized. Do you have any advice on how to diagnose the problem? 

Thank you very much for the support!

**Comment by vbuitvydas** [comment]
Hi @Jojeker, 

- Are you using LimeSDR-XTRX v1.2 version?
- Probably you have already checked that but, is board inserted properly into mini PCIe slot? There are small white connectors on the bottom side, check if latch of those connectors are closed. If they are open board bends a little and you can get some weird issues with PCIe connection. 
- Can you check if both LEDs are blinking when board is powered and inserted in mini PCIe slot?
- Was this board working before, or you were trying to resolve some issues by updating board? 

If you have access to PCIe adapter you can try to revive board trough JTAG, here are the instructions:
[jtag-programming](https://limesdr-xtrx.myriadrf.org/documentation/jtag-programming)

Regards, 
Vytautas

**Comment by Jojeker** [comment]
Hello,

we are using the LimeSDR-XTRX v1.2 and verified by checking the
printout on the PCB.
When the PC is powered on, both LEDs are both off; on a working unit
one LED is turned on continuously, while the other one is blinking.
The board was previously working and accessible via `limeDevice`.

We don't own a PCIe adapter but would very much like to order one if
possible. Do you have a resource on where to buy one from?

Is this the design you are using:
https://github.com/xtrx-sdr/xtrx-adapters/tree/main/PCIex2%20frontend ?

Best,
Eduard

**Comment by vbuitvydas** [comment]
Understood, if both LEDs are OFF then definitely bitstream on FPGA is not loaded. Probably there are some hardware faults or bitstream itself got somehow corrupted.  

I don't have info on PCIe adapter availability at the moment,  but there is a thread going on about it:
https://discourse.myriadrf.org/t/limesdr-xtrx-pcie-adapter-board/8222/10

Not the best option but if you feel comfortable soldering and have JTAG adapter you can solder some short wires directly on  JTAG pogo pins connector.  

Regards, 
Vytautas

**Comment by vbuitvydas** [comment]
Hi @Jojeker, 

do you need any further assistance? 

Regards, 
Vytautas

**Comment by Jojeker** [comment]
Hi Vytautas,

thanks for the assistance. We will try to re-flash asap and report the
result. For now, we should be set.

Cheers,
Eduard
