### ISSUE TITLE
Unable to read board's temperature sensor value

### ISSUE THREAD

**Issue by rjonaitis** [myriadrf/LimeSDR-XTRX_GW#2]
LimeSDR XTRX Reading board's temperature using CMD_ANALOG_VAL_RD reports success, but always return temperature value of 0.
https://github.com/myriadrf/LimeSDR-XTRX_GW/blob/a6fb00c81d7757e41c1f201df2923dbdce31d09f/software/cpu/src/main.c#L1342-L1366

**Comment by Tomserv-512** [comment]
Solved in master branch; gw  v1.12; commit short hash bdd0c69
